name: Build and publish Cockpit update plugin

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - run: npm run init

      - name: Pack dist folder
        run: tar -czvf cockpit-update.tar.gz -C dist/ .

      - name: Upload artifact
        uses: softprops/action-gh-release@v3
        with:
          files: ./cockpit-update.tar.gz
