name: Build and publish Cockpit update plugin

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm run init

      - name: Pack dist folder
        run: tar -czvf cockpit-update.tar.gz -C dist/ .

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./cockpit-update.tar.gz
          asset_name: cockpit-update.tar.gz
          asset_content_type: application/gzip
